### ISSUE TITLE
以后会支持其它的语音接口么？

### ISSUE THREAD

**Issue by Neomanbeta** [xqe2011/danmuji#1]
如题
因为win的tts读起来太机械了，以后会有计划支持edge的或者azure，或者阿里等其它的语音api么？

**Comment by xqe2011** [comment]
edge的tts需要联网才能使用，弹幕量较多的时候可能会影响延迟，azure,阿里这些需要收费的语音接口，我后期可能会考虑允许自定义语音API和SSMS格式文本。

**Comment by Neomanbeta** [comment]
好的，感谢回复。
