### ISSUE TITLE
[BUG]弹幕机内存使用异常

### ISSUE THREAD

**Issue by DouDouMi00** [xqe2011/danmuji#3]
弹幕机使用时，观察win10任务管理，弹幕机占用的内存一直在增加，长按`Ctrl+Alt+左方括号`这些快捷键可以使问题更明显，内存似乎未释放。奇怪的问题😕
`弹幕机版本v1.3.1`

**Comment by xqe2011** [comment]
我晚点去复现一下，极大概率和windows的tts接口有关

**Comment by DouDouMi00** [comment]
我还没找到原因，谢谢你提供思路。同时我还注意到`Ctrl+Alt+左方括号`这个快捷键，在长按时cpu占用也很高会到45%。

**Comment by xqe2011** [comment]
无法复现

## 测试环境
Python 3.11.4
启动指令`python .\launcher.py`
AMD 5600X
使用RDP远程桌面连接
音频输出设备为“远程音频”
测试直播间为某知名VUP的一场晚上直播全过程

## 测试场景
- 关闭所有过滤器，此时积压弹幕数达到3000+，未出现内存异常增长
- 启用进入直播间提示过滤器，其他依旧维持原样，此时弹幕数正常，未出现内存增长

内存泄漏可能与安全软件和所使用的音频输出设备有关，甚至有的时候和硬件有关，建议尝试一下注释tts中用于输出的`pygame`系列函数和用于tts合成的`synthesize_ssml_to_stream_async`排查一下是哪个模块导致的问题。部分安全软件会通过远程注入代码的方式检测运行的py脚本，可能也会导致类似于内存泄漏的情况。

**Comment by DouDouMi00** [comment]
我是运行exe文件的，会不会和这个有关系

**Comment by DouDouMi00** [comment]
我明天再试试吧，杀毒软件Microsoft Defender，i5-6500，安装完弹幕机v1.3.1，扫码登录，设置直播间号，然后按快捷键调语速就会内存泄露。快捷键按的时间越长，内存占的越多。我是本地运行，语音直接输出到喇叭。好奇怪🙁

**Comment by DouDouMi00** [comment]
我明天再试试吧，杀毒软件Microsoft Defender，i5-6500，安装完弹幕机v1.3.1，扫码登录，设置直播间号，然后按快捷键调语速就会内存泄露。快捷键按的时间越长，内存占的越多。我是本地运行，语音直接输出到喇叭。好奇怪🙁

**Comment by DouDouMi00** [comment]
应该是这个`synthesize_ssml_to_stream_async`模块导致的问题，我把之后的代码都删了问题依然存在。

**Comment by xqe2011** [comment]
`synthesize_ssml_to_stream_async`是系统调用，或许是windows的问题，话说内存异常增长的比例大概是多少

**Comment by DouDouMi00** [comment]
快捷键按一分钟，差不多1GB,就听弹幕一分钟5MB差不多了。

**Comment by DouDouMi00** [comment]
tts 模块最后我加了这句代码
```
async def tts(text, channel=0, config=None):
    .............
    channels = [{"lastRate": None, "lastVolume": None, "lastVoice": None, "synthesizer": speechsynthesis.SpeechSynthesizer()}] * 2
```
现在内存占用正常了，大概120-150MB左右，就是控制台一直在打印`[TTS] Use voice: Microsoft Huihui (zh-CN)"`我就先这样用吧，估计是windows的问题。

**Comment by xqe2011** [comment]
从修改的代码看，大约是windows的tts没有释放掉内存，我过段时间再去排查一下windows api看看是不是这个接口要做什么释放工作

**Comment by xqe2011** [comment]
我尝试了使用exe启动`v1.3.1`版本，依旧没有出现问题，可以提供一下你的电脑windows版本号和使用了哪一款tts引擎吗？电脑上是否有安装除了争渡读屏意外的可能会修改系统tts语音库的软件呢

**Comment by DouDouMi00** [comment]
```
版本	Windows 10 专业版
版本号	22H2
安装日期	‎2020/‎10/‎3
操作系统内部版本	19045.4046
体验	Windows Feature Experience Pack 1000.19053.1000.0
winsdk  1.0.0b9
Python 3.11.7
```
我没有安装任何读屏软件，tts引擎我自己没装过应该就是系统自带的吧。

**Comment by xqe2011** [comment]
尝试在`tts`函数尾部尾部添加
```
async def tts(text, channel=0, config=None):
........
    stream.close()
```

**Comment by xqe2011** [comment]
如果可以的话反馈一下，我把整个更改推上去

**Comment by DouDouMi00** [comment]
我记得close后，会显示xx已关闭，还得再初始化下，就和我那样改没啥区别了

**Comment by xqe2011** [comment]
关闭`stream`应该不会，关闭`synthesizer`才会

**Comment by DouDouMi00** [comment]
好了，好了！！加上这句代码就行了。
```
 async def tts(text, channel=0, config=None):
 ........
     stream.close()
```

**Comment by xqe2011** [comment]
f3329fedbd73aa0b956ac046d0462c1e12222fc1 已修复

**Comment by DouDouMi00** [comment]
测试完，问题已解决
