### ISSUE TITLE
源码编译失败

### ISSUE THREAD

**Issue by le45tx1m** [xqe2011/danmuji#4]
![QQ截图20240221205735](https://github.com/xqe2011/danmuji/assets/54882626/9fdb11e0-440a-41c0-8dbb-9094639c5dfd)

**Comment by le45tx1m** [comment]
这是要去下 xfgryujk 的库吗？

**Comment by le45tx1m** [comment]
看了一眼 blivechat ，果然是子模块拉漏了，clone时需要加上--recursive参数，不过到pip 那一步又出错了找不到 psutil 模块

![QQ截图20240221223732](https://github.com/xqe2011/danmuji/assets/54882626/f0e0ed15-c26b-482c-9b59-77f69413e4f2)

**Comment by xqe2011** [comment]
了解，这就更新一下文档

**Comment by xqe2011** [comment]
d0749b1a0dc130b67210aaf9aaab7594ff35f127 已修复
