### ISSUE TITLE
[BUG]弹幕机在读纯标点符号弹幕时，输出语音为空

### ISSUE THREAD

**Issue by DouDouMi00** [xqe2011/danmuji#5]
### 问题描述

弹幕机在读纯标点符号弹幕时，输出语音为空
例如`xxx发送了一条???`的弹幕，弹幕机只会读出 `xxx说`

### 环境信息

```

- 操作系统 Windows_10_22H2_19045.4046
- 企鹅弹幕机 v1.3.1

```

### 重现步骤

进入直播间发送一条纯标点的弹幕例如：
```
......
???
!!!!
```

**Comment by xqe2011** [comment]
这个其实是feature，因为当弹幕在刷`？？？`的时候，视障主播可以通过大量的空信息推测现在弹幕在刷标点符号从而猜测在说什么，但确实可以新增一个标点符号过滤器

**Comment by DouDouMi00** [comment]
我现在的做法是把，。？！这四个标点符号转换成中文播报。用了过滤器我觉得氛围感有点缺少。可以加个标点符号过滤器的开关，让用户自己选择。

**Comment by xqe2011** [comment]
确实，在写了

**Comment by xqe2011** [comment]
7b2721ea2c0bcc399bbecfcd9882b98f934be2b8 已增加

**Comment by DouDouMi00** [comment]
对了，这次增加的代码遇到`⁄(⁄ ⁄•⁄ω⁄•⁄ ⁄)⁄`这种符号表情会咋播报。我还没试。

**Comment by xqe2011** [comment]
我在测试的时候确实见到了这个表情，但没听清，似乎是把每个符号都念出来了

**Comment by DouDouMi00** [comment]
抽象

**Comment by DouDouMi00** [comment]
颜文字的播报，这个项目提供了颜文字对应的汉语拼音，或许可以试着转换出文字让弹幕机读出来。不过，在遇到没有匹配的颜文字，估计还是读每一个符号，这样听起来太奇怪。我感觉颜文字还是别念出来，直接忽略算了。
https://github.com/aoguai/rime_kaomoji_dict

**Comment by xqe2011** [comment]
如果没有在这个字典里有匹配的，那只能按照标点符号的方式来读出来，因为匹配不到的话，也没办法知道用户发的是颜文字，所以也无法过滤。
如果有匹配的，可以按照字典内的设定来读，但其实我更倾向于保留原来的样子，也就是按照标点符号的方式读，虽然听上去非常难绷，但可以和第1种保持一样的语义，除非我们能建立一个非常非常详细的字典，涵盖了绝大多数的颜文字，那样的话采用颜文字读法才合适一些。

**Comment by DouDouMi00** [comment]
颜文字的识别，下面这个项目里有实现了颜文字的发现切分和预测语义，也给出了识别颜文字更详细的正则表达式。`大概可能，能实现提示下用户这段可能是颜文字的功能吧。`不过我觉得保持一样的语义也不错，这个项目里也是需要能建立一个非常详细的字典来预测语义，并且在预测没有收录表情的语义上，准确度似乎并不高。
https://github.com/mattzheng/py-yanwenzi

**Comment by xqe2011** [comment]
确实可以用nlp来预测，这个项目有一个分支是携带的深度学习库的，当时的目的是为了智能去重，不过我对模型是否能比较精确的预测颜文字持消极态度
你提到的那个库他的实现思路是用正则提取之后再通过rouge比对确认表情属性，但我认为这里最核心的问题是正则提取不准确，或许我们可以用它收集的1800个数据训练一个表情提取模型出来，这应该不难，只不过有一个问题是我们如何在边缘侧运行这个模型，之前深度学习分支废弃的理由就是如果需要引入模型。即便是经过轻量化的onnxruntime+我自己量化的embeddings模型，也会使程序的安装包增加到1G大小

**Comment by DouDouMi00** [comment]
是的，正则提取可能不准确，可能还会造成其他问题。数据训练表情提取模型，我估计不好用，并且表情的语义也没有。引入深度模型性能消耗很大，1G的安装包，又是直播，可能还开个游戏，就为了提取一个表情不合适。那就用最开始的方案吧。

**Comment by xqe2011** [comment]
ff12bf3da54efc99da7c17d56d9df5c6d4659486 已加入，增加了过滤器开关和标点符号朗读开关

**Comment by DouDouMi00** [comment]
嗯，试用了新功能，新功能真的不错！开发好迅速，非常感谢您。
