### ISSUE TITLE
[Enhancement]增加当前弹幕延迟过高播报

### ISSUE THREAD

**Issue by DouDouMi00** [xqe2011/danmuji#6]
弹幕机能否增加一种弹幕延迟过高的播报。例如：当前弹幕延迟xx秒，积压弹幕有xx条。

**Comment by xqe2011** [comment]
现在可以通过查看延迟快捷键实现，或许确实可以增加积压弹幕数过大的时候的自动播报功能

**Comment by DouDouMi00** [comment]
大量弹幕时候，可能意识不到积压了很多弹幕，或者什么意外状况，自动播报可以提醒下用户。

**Comment by xqe2011** [comment]
功能写完了，今晚某只猫开播的话测试没问题就会推送

**Comment by DouDouMi00** [comment]
嗯，谢谢你，开发速度好快👍

**Comment by xqe2011** [comment]
ff12bf3da54efc99da7c17d56d9df5c6d4659486 已加入

**Comment by DouDouMi00** [comment]
谢谢你，我这边测试的没问题，非常感谢您。
